"""
RailBlock AI — Maintainability Prioritization (ML)
==================================================

Learns a prioritization model that ranks maintenance tasks by criticality so the
scheduler maximizes asset availability.

Why ML here: the previous engine used a fixed, hand-tuned scoring formula
(priority*0.5 + criticality*0.3 + dept*0.2). That weights are arbitrary and do
not adapt to the actual mix of defects, overdue age, and corridor traffic. This
module learns the mapping from task/defect/traffic features to a priority score,
calibrates it into a well-behaved [0, 1] probability, and exposes audit info so
the ranking is explainable.

Training data realism:
  * We only have a small synthetic snapshot, so larger data is generated by a
    deterministic augmentation routine (perturbing recorded examples). This is
    explicit and honest: the model is calibrated on synthetic-but-realistic data
    and the methodology is what we are demonstrating, not a claim of training on
    real Indian Railways telemetry.

Deployment is fully self-contained (scikit-learn + numpy), with a heuristic
fallback if the model cannot be built/loaded.
"""

from __future__ import annotations

import warnings
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

warnings.filterwarnings("ignore")

try:
    from sklearn.ensemble import GradientBoostingRegressor
    from sklearn.isotonic import IsotonicRegression
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import mean_squared_error
    _HAS_SKLEARN = True
except Exception:  # pragma: no cover - fallback path
    _HAS_SKLEARN = False

# ---------------------------------------------------------------------------
# Feature vocabulary (must stay in sync with _FEATURE_COLUMNS)
# ---------------------------------------------------------------------------

FEATURE_COLUMNS: List[str] = [
    "priority_enc",          # Critical=3 High=2 Medium=1 Low=0
    "criticality_score",     # 0..1 asset-level criticality from source data
    "dept_enc",              # S&T=2, Traction=1, Engineering=0
    "task_type_enc",         # Corrective=1, Preventive=0
    "defect_age_days",       # how long the linked defect has been open
    "severity_enc",          # Critical=3 High=2 Medium=1 Low=0 (defect severity)
    "resource_count",        # number of crews/machines needed
    "train_density",         # number of scheduled trains on the section
    "duration_minutes",      # work duration
    "has_dependency",        # 1 if the task depends on another
    "crit_x_age",            # interaction: criticality * defect_age
    "dept_crit",             # interaction: dept_enc * criticality
    "density_crit",          # interaction: train_density * criticality
]

PRIORITY_MAP = {"Critical": 3, "High": 2, "Medium": 1, "Low": 0}
DEPT_MAP = {"Signal & Telecommunication": 2, "Traction Distribution": 1, "Engineering": 0}
TASK_TYPE_MAP = {"Corrective Maintenance": 1, "Preventive Maintenance": 0}
SEVERITY_MAP = {"Critical": 3, "High": 2, "Medium": 1, "Low": 0}


def _train_density_for_section(section_id: str, train_schedule: Optional[List[dict]] = None) -> float:
    if not train_schedule:
        return 12.0  # default: NDLS-GZB-UP / GZB-MTC-DN both carry 12 trains
    matches = [t for t in train_schedule if str(t.get("track_section", "")) == section_id]
    return float(len(matches)) if matches else 6.0


def build_features(task: dict, defect: Optional[dict], train_schedule: Optional[List[dict]] = None) -> Dict[str, float]:
    """Transform a maintenance task (+ optionally its linked defect) into feature vector."""
    priority = str(task.get("priority", "Medium"))
    dept = str(task.get("department", "Engineering"))
    task_type = str(task.get("task_type", "Preventive Maintenance"))
    crit_raw = float(task.get("criticality_score", 0.5) or 0.5)
    age_days = float((defect or {}).get("age_days", 0) or 0)
    severity = str((defect or {}).get("severity", "Low"))
    resources = task.get("required_resources", []) or []
    deps = task.get("dependencies", []) or []
    duration = float(task.get("duration_minutes", 60) or 60)
    section = str(task.get("track_section", ""))

    priority_enc = PRIORITY_MAP.get(priority, 1.0)
    dept_enc = DEPT_MAP.get(dept, 0.0)
    task_type_enc = TASK_TYPE_MAP.get(task_type, 0.0)
    severity_enc = SEVERITY_MAP.get(severity, 1.0)
    density = _train_density_for_section(section, train_schedule)

    return {
        "priority_enc": float(priority_enc),
        "criticality_score": float(min(1.0, max(0.0, crit_raw))),
        "dept_enc": float(dept_enc),
        "task_type_enc": float(task_type_enc),
        "defect_age_days": float(min(age_days, 365.0)),
        "severity_enc": float(severity_enc),
        "resource_count": float(len(resources)),
        "train_density": float(density),
        "duration_minutes": float(duration),
        "has_dependency": 1.0 if len(deps) > 0 else 0.0,
    }


def feature_vector(feat: Dict[str, float]) -> np.ndarray:
    """Expand a raw feature dict into the full (interaction-augmented) row."""
    p = feat["priority_enc"]
    c = feat["criticality_score"]
    d = feat["dept_enc"]
    a = feat["defect_age_days"]
    dens = feat["train_density"]
    return np.array([
        p, c, d,
        feat["task_type_enc"],
        a,
        feat["severity_enc"],
        feat["resource_count"],
        dens,
        feat["duration_minutes"],
        feat["has_dependency"],
        c * a,              # crit_x_age
        d * c,              # dept_crit
        dens * c,           # density_crit
    ], dtype=np.float64)


class PriorityModel:
    """Gradient-boosted regressor calibrated into a monotonically usable score.

    The model targets the *blended priority* label (0..1) built from the source
    priority tier, the defect severity and the defect age. It is then fitted
    through an isotonic calibrator so the output is a clean [0,1] probability
    that can be compared across tasks.
    """

    def __init__(self, seed: int = 42):
        self.seed = seed
        self.model: Optional[Any] = None
        self.calibrator: Optional[Any] = None
        self.scaler = StandardScaler() if _HAS_SKLEARN else None
        self.trained = False
        self.metrics: Dict[str, Any] = {}

    # -- label construction -------------------------------------------------

    def make_labels(self, tasks: List[dict], defects_by_task: Dict[str, dict]) -> np.ndarray:
        labels = []
        for task in tasks:
            defect = defects_by_task.get(str(task.get("task_id", "")), {})
            priority_enc = PRIORITY_MAP.get(str(task.get("priority", "Medium")), 1.0) / 3.0
            severity_enc = SEVERITY_MAP.get(str(defect.get("severity", "Low")), 1.0) / 3.0
            age = float(defect.get("age_days", 0) or 0)
            age_norm = min(age / 90.0, 1.0)  # cap at 90 days for the age term
            crit = float(task.get("criticality_score", 0.5) or 0.5)
            # blended ground-truth-ish label emphasizing criticality
            label = 0.55 * priority_enc + 0.20 * severity_enc + 0.15 * age_norm + 0.10 * crit
            labels.append(min(label, 1.0))
        return np.array(labels, dtype=np.float64)

    # -- data preparation ---------------------------------------------------

    def _matrix(self, tasks: List[dict], defects_by_task: Dict[str, dict],
                train_schedule: Optional[List[dict]] = None) -> np.ndarray:
        rows = []
        for task in tasks:
            defect = defects_by_task.get(str(task.get("task_id", "")), {})
            feat = build_features(task, defect if defect else None, train_schedule)
            rows.append(feature_vector(feat))
        X = np.vstack(rows)
        if self.scaler is not None:
            X = self.scaler.fit_transform(X)
        return X

    # -- training -----------------------------------------------------------

    def train(self, tasks: List[dict], defects_by_task: Dict[str, dict],
              train_schedule: Optional[List[dict]] = None, augment_factor: int = 4) -> Dict[str, Any]:
        """Fit + calibrate the model on the (augmented) task snapshot."""
        if not _HAS_SKLEARN:
            self.trained = False
            return {"trained": False, "reason": "scikit-learn unavailable"}

        base_tasks = [t for t in tasks if t.get("task_id")]
        if len(base_tasks) < 6:
            self.trained = False
            return {"trained": False, "reason": "not enough tasks to train"}

        # Build a larger, representative dataset via bounded perturbations.
        rng = np.random.default_rng(self.seed)
        all_tasks: List[dict] = []
        for t in base_tasks:
            all_tasks.append(t)
            for _ in range(augment_factor - 1):
                noise = {
                    "criticality_score": float(np.clip(
                        float(t.get("criticality_score", 0.5)) + rng.normal(0, 0.05), 0, 1)),
                    "priority": t.get("priority", "Medium"),
                    "duration_minutes": max(15, int(float(t.get("duration_minutes", 60)) + rng.integers(-8, 9))),
                }
                copy = {**t, **noise}
                copy["task_id"] = f"{t['task_id']}-aug{rng.integers(1000, 9999)}"
                all_tasks.append(copy)

        X = self._matrix(all_tasks, defects_by_task, train_schedule)
        y = self.make_labels(all_tasks, defects_by_task)

        # 60/20/20 split: train (fit GBR) / calibrate (fit isotonic) / test.
        from sklearn.model_selection import train_test_split
        buckets = np.round(y * 4)
        X_tr, X_te, y_tr, y_te = train_test_split(
            X, y, test_size=0.40, random_state=self.seed, stratify=buckets)
        # further carve the calibration subset from the non-test portion
        buckets_c = np.round(y_tr * 4)
        X_cal, X_tr, y_cal, y_tr = train_test_split(
            X_tr, y_tr, test_size=0.50, random_state=self.seed, stratify=buckets_c)

        base = GradientBoostingRegressor(
            n_estimators=180, learning_rate=0.06, max_depth=3,
            min_samples_leaf=5, subsample=0.9, random_state=self.seed, loss="squared_error",
        )
        base.fit(X_tr, y_tr)

        # Fit the isotonic calibrator ONLY on the calibration split, then verify
        # it on the untouched test split (honest, not memorised).
        cal_raw = base.predict(X_cal)
        iso = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds="clip")
        iso.fit(cal_raw, y_cal)

        self.model = base
        self.calibrator = iso
        self.trained = True

        te_raw_base = base.predict(X_te)
        te_cal = self.calibrator.predict(te_raw_base)
        test_rmse = float(np.sqrt(mean_squared_error(y_te, te_cal)))
        # Expected Calibration Error (ECE) on the test split.
        ece = self._expected_calibration_error(y_te, te_cal)
        self.metrics = {
            "trained": True,
            "n_train": int(X_tr.shape[0]),
            "n_calibrate": int(X_cal.shape[0]),
            "n_test": int(X_te.shape[0]),
            "feature_count": int(X.shape[1]),
            "calibrated_test_rmse": test_rmse,
            "calibrated_test_r2": float(1 - np.sum((y_te - te_cal) ** 2) / np.sum((y_te - np.mean(y_te)) ** 2)),
            "test_ece": ece,
            "engine": "GradientBoosting + Isotonic (scikit-learn)",
        }
        return self.metrics

    @staticmethod
    def _expected_calibration_error(y_true: np.ndarray, y_prob: np.ndarray, n_bins: int = 8) -> float:
        """Mean absolute deviation of predicted probability from empirical rate."""
        bins = np.linspace(0.0, 1.0, n_bins + 1)
        acc = np.zeros(n_bins)
        conf = np.zeros(n_bins)
        cnt = np.zeros(n_bins)
        idx = np.clip(np.digitize(y_prob, bins[1:-1]), 0, n_bins - 1)
        for i in range(n_bins):
            mask = idx == i
            if mask.sum() == 0:
                continue
            cnt[i] = mask.sum()
            conf[i] = y_prob[mask].mean()
            acc[i] = y_true[mask].mean()
        return float(np.sum(cnt * np.abs(acc - conf)) / cnt.sum())

    # -- inference ----------------------------------------------------------

    def predict(self, feat: Dict[str, float]) -> Tuple[float, bool]:
        """Return (calibrated score in [0,1], used_model_bool)."""
        if not (self.trained and _HAS_SKLEARN):
            return float(self._heuristic_score(feat)), False
        x = np.array([feature_vector(feat)])
        if self.scaler is not None:
            x = self.scaler.transform(x)
        raw = float(self.model.predict(x)[0])
        prob = float(self.calibrator.predict([raw])[0])
        return float(np.clip(prob, 0.0, 1.0)), True

    def explain(self, feat: Dict[str, float]) -> Dict[str, float]:
        """Return the raw feature dict (for the audit/debug payload)."""
        return dict(feat)

    # -- heuristic fallback ------------------------------------------------

    @staticmethod
    def _heuristic_score(feat: Dict[str, float]) -> float:
        """Fallback: the legacy hand-tuned formula (never throws).

        Mirrors the original PrioritizationEngine weights so worst-case behaviour
        matches what the demo already shipped with.
        """
        priority_rev = {3.0: 0.95, 2.0: 0.75, 1.0: 0.50, 0.0: 0.25}
        priority_w = priority_rev.get(round(feat.get("priority_enc", 1.0)), 0.5)
        dept_rev = {2: 0.9, 1: 0.85, 0: 0.8}
        dept_factor = dept_rev.get(int(round(feat.get("dept_enc", 0.0))), 0.7)
        crit = feat.get("criticality_score", 0.5)
        return round(priority_w * 0.5 + crit * 0.3 + dept_factor * 0.2, 3)


# A single module-level model built lazily on first use.
_model: Optional[PriorityModel] = None


def get_model() -> PriorityModel:
    global _model
    if _model is None:
        _model = PriorityModel()
    return _model
